### PR TITLE
Added a fix to reset enabledClass on nanoScroller.reset()

### PR DESCRIPTION
**Pull request by jeradrutnam**

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks!

**Comment by jeradrutnam** [comment]
You are welcome! Please review and merge the PR. Hope it will be available in the next release. :)

**Comment by jeradrutnam** [comment]
@kristerkari: Just checking the status. Will there be a minor release with this fix?

**Comment by jamesflorentino** [comment]
Thanks @jeradrutnam 👍

**Comment by jeradrutnam** [comment]
You welcome @jamesflorentino, thanks for merging.

**Pull request merged**
