### PR TITLE
Moved modifying classes to options

### PR DESCRIPTION
**Pull request by bashkos**
Some people may want to name modifying classes in accordance with the adopted methodology. So I moved all modifying classes to options.

I hope it will be useful.

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks! Looks solid, I'll try to get this merged soonish.

**Comment by bashkos** [comment]
Hi again. Can I rely on the implementation of these minor tweaks. Then I would have removed the fork, and would use the library from the main repository

**Comment by kristerkari** [comment]
@bashkos Yeah sorry about not merging this. Changes look good so I don't see a reason not to merge this. I just need to see that they don't break any functionality.

**Comment by kristerkari** [comment]
Merged!

**Comment by bashkos** [comment]
Thanks a lot :)

**Pull request merged**
